### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Xeverous** [kosenko/ui#10]
I haven't got a responce about CMake support issue after 2 months.

Wondering if the author is still active or any of the watchers. I have some plans about significant extension of the library [as written in this reddit thread](https://www.reddit.com/r/cpp/comments/cju3h3/reviving_boostui/) but if no one is here I will just fork it and go with additions under a different library name.

**Comment by kosenko** [comment]
Yes, project alive.
