### ISSUE TITLE
allegro 5 support?

### ISSUE THREAD

**Issue by Shadowblitz16** [kosenko/ui#12]
is it possible to use allegro 5 with this?

the things I am wondering to do are..
- pass allegro bitmaps instead of boost.ui images
- pass allegro colors instead of boost.ui colors
- host allegro windows in a control

**Comment by kosenko** [comment]
I don't know, I'm not familiar with Allegro 5.
- You can load images from binary stream (files) using `boost::image::load()` function.
- You can set/get color channels.
- I don't know how Allegro 5 works with windows and controls.
