### ISSUE TITLE
is this library's dependencies statically linked?

### ISSUE THREAD

**Issue by Shadowblitz16** [kosenko/ui#13]
is this library's dependencies statically linked?
if not can they be so we don't have to install them before we use this?

**Comment by kosenko** [comment]
Yes, it is possible to link Boost.UI and all dependencies statically. So you able to have one executable file.

**Comment by Shadowblitz16** [comment]
@kosenko no I mean is boost.ui statically linked to its dependancies

**Comment by kosenko** [comment]
Boost.UI can be linked to its dependencies either statically or dynamically as you wish.
