### ISSUE TITLE
build boost.ui project using visual studio 2019

### ISSUE THREAD

**Issue by muha0143** [kosenko/ui#14]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'libboost_ui-vc142-mt-gd-x32-1_70.lib'	UIDemo	C:\Users\Muhammed\source\repos\UIDemo\UIDemo\LINK	1	

I got this error while I am trying to build a simple project for the first time using Boost.UI 

when I looked at $(BOOST_ROOT)\stage\lib : I didnot find " libboost_ui-vc142-mt-gd-x32-1_70.lib " although I did the build steps on the build Boost.UI github repos 
[build boost.ui](https://github.com/kosenko/ui/tree/master/build)

@kosenko 👍  :

**Comment by kosenko** [comment]
Sorry, but I didn't try to build Boost.UI using Visual Studio 2019. Do you have any errors during Boost.UI build? Or it just build nothing? Could you please to try to run examples?

**Comment by muha0143** [comment]
I build Boost.UI using b2 that is part of boost library, where I followed the direction of the [Build Boost.UI](https://github.com/kosenko/ui/tree/master/build) .. but, this did not produce .lib file for the boost.UI which is needed to compile any project depend on this library. which is should be in 
$(BOOST_ROOT)\stage\lib but it's eventually did not exist. 
the error of building the project is above .. 

my question exactly is what i did wrong that is why the .lib file is missing. 
the building procedure that i followed to build boost.ui are:

1: i move the "ui" directory to "$(BOOST_ROOT)\libs\"

2:  i download wxwidgets and setup environment variables $(WXWIN) : wxwidgets installing directory.

3: i execute the following commands : 

PC>   b2 libs/ui/build/ link=static
PC>   b2 libs/ui/test/ link=static
PC>   b2 libs/ui/example/ link=static
PC>   b2 libs/ui/example/cpp11/ link=static

* all the executions did not  failed or show error message . 
if you want the executions output I could send them here.
