### ISSUE TITLE
ui::window not working properly

### ISSUE THREAD

**Issue by UltraBlackLinux** [kosenko/ui#24]
Hey there,
I want to create a window with a frame and I wanted to achieve this with ui::window, but whenever I try to create it, nomatter how I do it, I always end up with `/src/gtk/window.cpp(2787): assert ""parent"" failed in PreCreation(): Must have non-NULL parent` or `libs/ui/src/window.cpp(54): assert ""impl"" failed in title(): Widget should be created` when using `title()`.
Here is an example:
```
class Window : public ui::window {
public:
    Window() : ui::window() {
	ui::vbox layout(*this);
    }
}
```
Why is it not working?
Thanks!

**Comment by kosenko** [comment]
`boost::ui::window` is an abstract class that can't be created, please use `frame` or `dialog` classes and specify title.
