### ISSUE TITLE
theming support

### ISSUE THREAD

**Issue by Xeverous** [kosenko/ui#8]
Is is possible to add any themes (being able not to look like very classic OS application) or make changes to eg background color?

**Comment by kosenko** [comment]
Themes are no supported, but it is possible to change theme if underling native toolkit supports themes. Changing background and text color isn't implemented yet. But it is possible to draw own widget using boost::ui::canvas.

**Comment by UltraBlackLinux** [comment]
theming is a thing using e.g. gnome-tweaks, on Linux at least
